files_with_version_number = {
  './package.json' => ['"version": "{x}"'],
  './scripts/docs/index.html' => ['purchases-js-docs/{x}/'],
  './.version' => ['{x}'],
  './src/helpers/constants.ts' => ['VERSION = "{x}"']
}

repo_name = 'purchases-js'
changelog_latest_path = './CHANGELOG.latest.md'
changelog_path = './CHANGELOG.md'

before_all do
  setup_circle_ci
end

desc "Replaces version numbers, updates changelog and creates PR"
lane :bump do |options|
  bump_version_update_changelog_create_pr(
    current_version: current_version_number,
    changelog_latest_path: changelog_latest_path,
    changelog_path: changelog_path,
    files_to_update: files_with_version_number,
    repo_name: repo_name,
    github_rate_limit: options[:github_rate_limit],
    editor: options[:editor],
    next_version: options[:next_version],
    automatic_release: options[:automatic_release],
    is_prerelease: options[:is_prerelease]
  )
end

desc "Automatically bumps version, replaces version numbers, updates changelog and creates PR"
lane :automatic_bump do |options|
  next_version, type_of_bump = determine_next_version_using_labels(
    repo_name: repo_name,
    github_rate_limit: options[:github_rate_limit]
  )
  options[:next_version] = next_version
  options[:automatic_release] = true
  if type_of_bump == :skip
    UI.message('Skipping automatic bump since the next version doesn\'t include public facing changes')
    next
  end
  if type_of_bump == :major
    UI.message('Skipping automatic bump since the next version is a major release')
    next
  end
  bump(options)
end

desc "Creates github release"
lane :github_release do |options|
  release_version = options[:version]
  create_github_release(
    version: release_version,
    repo_name: repo_name,
    github_api_token: ENV["GITHUB_TOKEN"],
    changelog_latest_path: changelog_latest_path
  )
end

desc "Creates GitHub release and publishes react-native-purchases and react-native-purchases-ui"
lane :release do |options|
  version_number = current_version_number
  is_prerelease = Gem::Version.new(version_number).prerelease?

  args = [
    'npm',
    'publish',
    is_prerelease ? '--tag next' : nil
  ].compact

  Dir.chdir(get_root_folder) do
    sh(args)
  end
  github_release(version: version_number)
end

desc "Generate docs"
lane :generate_docs do
  version_number = current_version_number
  docs_repo_base_url = "https://github.com/RevenueCat/"
  docs_repo_name = "purchases-js-docs"
  docs_repo_url = File.join(docs_repo_base_url, docs_repo_name)

  Dir.mktmpdir do |docs_generation_folder|
    # Must be run from the root dir
    Dir.chdir("..") do
      sh(
        "npx",
        "typedoc",
        "--out",
        docs_generation_folder
      )

      docs_index_path = File.join(Dir.pwd, "scripts/docs/index.html")

      # clone docs repo
      Dir.mktmpdir do |docs_repo_clone_dir|
        Dir.chdir(docs_repo_clone_dir) do
          sh("git", "clone", docs_repo_url)
          Dir.chdir(docs_repo_name) do
            # copy docs generated in the previous step into the docs folder and push the changes
            docs_destination_folder = "docs/#{version_number}"
            index_destination_path = "docs/index.html"
            FileUtils.cp_r docs_generation_folder, docs_destination_folder
            FileUtils.cp docs_index_path, index_destination_path

            # using sh instead of fastlane commands because fastlane would run from the repo root
            sh("git", "add", docs_destination_folder)
            sh("git", "add", index_destination_path)
            sh("git", "commit", "-m", "Update documentation for #{version_number}")
            sh("git", "push")
          end
        end
      end
    end
  end
end

desc "Tag current branch with current version number"
lane :tag_current_branch do |options|
  version_number = current_version_number
  check_no_git_tag_exists(version_number)

  add_git_tag(tag: version_number)
  push_git_tags(tag: version_number)
end

###############################################################################
# Helper functions 🤜🤛                                                      #
###############################################################################

def current_version_number
  File.read("../.version").strip
end

def get_root_folder
  return File.expand_path('../../', __FILE__)
end

def check_no_git_tag_exists(version_number)
  if git_tag_exists(tag: version_number, remote: true, remote_name: 'origin')
    raise "git tag with version #{version_number} already exists!"
  end
end
