schema-version = 1

[package]
title = "Purchase Tester"
version = "0.1.0"
id = "com.revenuecat.purchases_sample"

[components]
[[components.interactive]]
id = "com.revenuecat.purchases_sample.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]
