name: Test (rcbilling-demo)

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: npm install purchases-js
        run: |
          npm ci
        env:
          CI: true

      - name: npm build purchases-js
        run: |
          npm run build
        env:
          CI: true

      - name: npm install
        working-directory: ./examples/rcbilling-demo
        run: |
          npm ci
        env:
          CI: true

      - name: npm lint
        working-directory: ./examples/rcbilling-demo
        run: |
          npm run lint
        env:
          CI: true

      - name: check format
        working-directory: ./examples/rcbilling-demo
        run: |
          npm run prettier:ci
        env:
          CI: true

      - name: npm build
        working-directory: ./examples/rcbilling-demo
        run: |
          npm run build
        env:
          CI: true
          VITE_RC_API_KEY: ${{ secrets.RC_API_KEY }}
          VITE_RC_STRIPE_ACCOUNT_ID: ${{ secrets.RC_STRIPE_ACCOUNT_ID }}
          VITE_RC_STRIPE_PK_KEY: ${{ secrets.RC_STRIPE_PK_KEY }}
