# Simple workflow for deploying static content to GitHub Pages
name: Deploy (rcbilling-demo)

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: npm install purchases-js
        run: |
          npm ci
        env:
          CI: true

      - name: npm build purchases-js
        run: |
          npm run build
        env:
          CI: true

      - name: npm install
        working-directory: ./examples/rcbilling-demo
        run: |
          npm ci
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: npm lint
        working-directory: ./examples/rcbilling-demo
        run: |
          npm run lint
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: check format
        working-directory: ./examples/rcbilling-demo
        run: |
          npm run prettier:ci
        env:
          CI: true

      - name: npm build
        working-directory: ./examples/rcbilling-demo
        run: |
          npm run build
        env:
          CI: true
          VITE_RC_API_KEY: ${{ secrets.RC_API_KEY }}

      - name: Sync files to S3 bucket
        working-directory: ./examples/rcbilling-demo
        run: |
          aws s3 sync dist s3://app-rcbillingdemo.revenuecat.com --delete

      - name: Fix cache control on index.html
        working-directory: ./examples/rcbilling-demo
        run: |
          aws s3 cp --cache-control 'no-cache' --content-type 'text/html' s3://app-rcbillingdemo.revenuecat.com/index.html s3://app-rcbillingdemo.revenuecat.com/index.html --metadata-directive REPLACE

      - name: Invalidate Cloudfront Distribution
        working-directory: ./examples/rcbilling-demo
        run: |
          aws cloudfront create-invalidation --distribution-id E31EVZCWLXEOFB --paths "/*"
